function EvalMtx = getEvalMtx (RSS,SAW,GRA,TOPSIS,VIKOR)

%take a closer look, compose eval matrices 5x6 (algorithms by parameters)
traffic = fieldnames(VIKOR.mean);  %or gra or saw, doesn't matter, the fields are the same
load = fieldnames(VIKOR.mean.conv);
for i=1:numel(traffic)
    for j=1:numel(load)
        EvalMtx.(traffic{i}).(load{j}) = ...
        [RSS.mean.(traffic{i}).(load{j}).availBitrate  RSS.mean.(traffic{i}).(load{j}).throughput...
         RSS.mean.(traffic{i}).(load{j}).delay RSS.mean.(traffic{i}).(load{j}).jitter   ...
         RSS.mean.(traffic{i}).(load{j}).loss RSS.mean.(traffic{i}).(load{j}).cost RSS.mean.(traffic{i}).(load{j}).numberOfHO ...
         RSS.mean.(traffic{i}).(load{j}).RSSI;
         SAW.mean.(traffic{i}).(load{j}).availBitrate  SAW.mean.(traffic{i}).(load{j}).throughput...
         SAW.mean.(traffic{i}).(load{j}).delay SAW.mean.(traffic{i}).(load{j}).jitter   ...
         SAW.mean.(traffic{i}).(load{j}).loss SAW.mean.(traffic{i}).(load{j}).cost SAW.mean.(traffic{i}).(load{j}).numberOfHO ...
         SAW.mean.(traffic{i}).(load{j}).RSSI;
         GRA.mean.(traffic{i}).(load{j}).availBitrate  GRA.mean.(traffic{i}).(load{j}).throughput...
         GRA.mean.(traffic{i}).(load{j}).delay GRA.mean.(traffic{i}).(load{j}).jitter   ...
         GRA.mean.(traffic{i}).(load{j}).loss GRA.mean.(traffic{i}).(load{j}).cost GRA.mean.(traffic{i}).(load{j}).numberOfHO ...
         GRA.mean.(traffic{i}).(load{j}).RSSI;
         TOPSIS.mean.(traffic{i}).(load{j}).availBitrate  TOPSIS.mean.(traffic{i}).(load{j}).throughput...
         TOPSIS.mean.(traffic{i}).(load{j}).delay TOPSIS.mean.(traffic{i}).(load{j}).jitter   ...
         TOPSIS.mean.(traffic{i}).(load{j}).loss TOPSIS.mean.(traffic{i}).(load{j}).cost TOPSIS.mean.(traffic{i}).(load{j}).numberOfHO ...
         TOPSIS.mean.(traffic{i}).(load{j}).RSSI;
         VIKOR.mean.(traffic{i}).(load{j}).availBitrate  VIKOR.mean.(traffic{i}).(load{j}).throughput...
         VIKOR.mean.(traffic{i}).(load{j}).delay VIKOR.mean.(traffic{i}).(load{j}).jitter   ...
         VIKOR.mean.(traffic{i}).(load{j}).loss VIKOR.mean.(traffic{i}).(load{j}).cost VIKOR.mean.(traffic{i}).(load{j}).numberOfHO ...
         VIKOR.mean.(traffic{i}).(load{j}).RSSI]
    end
end